
package com.sap.document.sap.rfc.functions;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "D50", targetNamespace = "urn:sap-com:document:sap:rfc:functions", wsdlLocation = "file:/C:/Users/j1010591/Desktop/WSDL_Development/wsdl_file_zbc_event_raise.wsdl")
public class D50
    extends Service
{

    private final static URL D50_WSDL_LOCATION;
    private final static WebServiceException D50_EXCEPTION;
    private final static QName D50_QNAME = new QName("urn:sap-com:document:sap:rfc:functions", "D50");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/j1010591/Desktop/WSDL_Development/wsdl_file_zbc_event_raise.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        D50_WSDL_LOCATION = url;
        D50_EXCEPTION = e;
    }

    public D50() {
        super(__getWsdlLocation(), D50_QNAME);
    }

    public D50(WebServiceFeature... features) {
        super(__getWsdlLocation(), D50_QNAME, features);
    }

    public D50(URL wsdlLocation) {
        super(wsdlLocation, D50_QNAME);
    }

    public D50(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, D50_QNAME, features);
    }

    public D50(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public D50(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZBCEVENTRAISEWEB
     */
    @WebEndpoint(name = "D50")
    public ZBCEVENTRAISEWEB getD50() {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "D50"), ZBCEVENTRAISEWEB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZBCEVENTRAISEWEB
     */
    @WebEndpoint(name = "D50")
    public ZBCEVENTRAISEWEB getD50(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:rfc:functions", "D50"), ZBCEVENTRAISEWEB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (D50_EXCEPTION!= null) {
            throw D50_EXCEPTION;
        }
        return D50_WSDL_LOCATION;
    }

}
