
package com.sap.document.sap.rfc.functions;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZBC_EVENT_RAISE_WEB", targetNamespace = "urn:sap-com:document:sap:rfc:functions")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZBCEVENTRAISEWEB {


    /**
     * 
     * @param eventparm
     * @param eventid
     * @param targetINSTANCE
     * @return
     *     returns java.lang.String
     * @throws ZBCEVENTRAISEException
     */
    @WebMethod(operationName = "ZBC_EVENT_RAISE", action = "urn:sap-com:document:sap:rfc:functions:ZBC_EVENT_RAISE_WEB:ZBC_EVENT_RAISERequest")
    @WebResult(name = "EV_SUCCESS", targetNamespace = "")
    @RequestWrapper(localName = "ZBC_EVENT_RAISE", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZBCEVENTRAISE")
    @ResponseWrapper(localName = "ZBC_EVENT_RAISEResponse", targetNamespace = "urn:sap-com:document:sap:rfc:functions", className = "com.sap.document.sap.rfc.functions.ZBCEVENTRAISEResponse")
    public String zbcEVENTRAISE(
        @WebParam(name = "EVENTID", targetNamespace = "")
        String eventid,
        @WebParam(name = "EVENTPARM", targetNamespace = "")
        String eventparm,
        @WebParam(name = "TARGET_INSTANCE", targetNamespace = "")
        String targetINSTANCE)
        throws ZBCEVENTRAISEException
    ;

}
